name: Build FlooCast

on:
  push:
    branches: [ precompiled ]
  pull_request:
    branches: [ precompiled ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: precompiled

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (Linux only)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gir1.2-appindicator3-0.1

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pystray notify-py pyserial serial-tool certifi

    - name: Build with PyInstaller
      run: pyinstaller FlooCast.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: FlooCast-${{ runner.os }}
        path: dist/*