name: Build FlooCast

on:
  push:
    branches: [ precompiled ]
  pull_request:
    branches: [ precompiled ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.9
          - os: windows-latest
            python-version: 3.9
          - os: macos-latest
            python-version: 3.9

    steps:
    - uses: actions/checkout@v2
      with:
        ref: precompiled

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (Linux only)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gir1.2-appindicator3-0.1

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pystray notify-py pyserial serial-tool certifi

    - name: Build with PyInstaller (macOS Universal)
      if: runner.os == 'macOS'
      run: |
        # Build for Intel
        pyinstaller --clean --distpath dist/FlooCast-x86_64 main.spec

        # Build for Apple Silicon
        ARCHFLAGS="-arch arm64" pyinstaller --clean --distpath dist/FlooCast-arm64 main.spec

        # Create universal binary
        lipo -create -output dist/FlooCast.app/Contents/MacOS/FlooCast \
          dist/FlooCast-x86_64.app/Contents/MacOS/FlooCast \
          dist/FlooCast-arm64.app/Contents/MacOS/FlooCast

        # Copy over the arm64 Info.plist as it will have the correct binary name
        cp dist/FlooCast-arm64.app/Contents/Info.plist dist/FlooCast.app/Contents/Info.plist

        # Optional: Remove the architecture-specific .app bundles
        rm -rf dist/FlooCast-x86_64.app dist/FlooCast-arm64.app

    - name: Build with PyInstaller (Non-macOS)
      if: runner.os != 'macOS'
      run: |
        # Build
        pyinstaller --clean main.spec

        # Optional: Remove the existing output directory
        rm -rf dist/FlooCast

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: FlooCast-${{ runner.os }}
        path: dist/*